ddp:
  ddp_enable: false
  world_size: 1
  gpus:
  - 0
  port: '12351'
model:
  num_layers: 18
  weights_init: true
  depth_model: fsm
  pose_model: front
data:
  data_path: /data/ddad/ddad.json
  log_dir: ./results/
  dataset: ddad
  back_context: 1
  forward_context: 1
  depth_type: lidar
  cameras:
  - camera_01
  - camera_05
  - camera_06
  - camera_07
  - camera_08
  - camera_09
  train_requirements: (gt_pose, mask)
  val_requirements: (gt_pose, gt_depth, mask)
  rgb_root: /data/ddad
  rgb_ext: .png
training:
  height: 384
  width: 640
  scales:
  - 0
  frame_ids:
  - 0
  - -1
  - 1
  batch_size: 1
  num_workers: 0
  learning_rate: 0.0001
  num_epochs: 20
  scheduler_step_size: 15
  aug_depth: false
  syn_visualize: false
  min_depth: 1.5
  max_depth: 200.0
  spatio: true
  spatio_temporal: true
  intensity_align: true
  focal_length_scale: 300
  flip_version: 5
loss:
  disparity_smoothness: 0.1
  spatio_coeff: 0.03
  spatio_tempo_coeff: 0.1
  pose_loss_coeff: 0.0
  spatial_depth_consistency_loss_weight: 0.001
  spatial_depth_consistency_type: pre
  sp_tp_recon_con_loss_weight: 0.2
eval:
  eval_batch_size: 4
  eval_num_workers: 8
  eval_min_depth: 0
  eval_max_depth: 200
  eval_visualize: false
  syn_visualize: false
  syn_idx: None
load:
  pretrain: false
  weights: weights_19
  models_to_load:
  - depth_net
logging:
  early_phase: 2000
  log_frequency: 100
  late_log_frequency: 1000
  save_frequency: 1
